// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:beerco/features/order/data/models/order_model.dart';
import 'package:beerco/features/table/data/models/member_model.dart';
import 'package:beerco/features/table/data/models/table_event_model.dart';
import 'package:beerco/features/table/data/models/table_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MemberModelAdapter());
    registerAdapter(OrderModelAdapter());
    registerAdapter(TableEventModelAdapter());
    registerAdapter(TableModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MemberModelAdapter());
    registerAdapter(OrderModelAdapter());
    registerAdapter(TableEventModelAdapter());
    registerAdapter(TableModelAdapter());
  }
}
